### ISSUE TITLE
Support for gradle build variants

### ISSUE THREAD

**Issue by jay-jlm** [jug6ernaut/DataBindingAdapter#4]
I started to get errors like this, after refactoring previously working code to support Android product flavors:

`Caused by: io.jug6ernaut.databinding.DataBindingAdapter$BindingException: java.lang.ClassNotFoundException: com.myproject.promo.BR
                                                                             at io.jug6ernaut.databinding.DataBindingAdapter.createBindingAdapter(DataBindingAdapter.java:133)
                                                                             at io.jug6ernaut.databinding.DataBindingAdapter.setAdapter(DataBindingAdapter.java:109)
                                                                             at br.com.avido.uget.databinding.FragmentTicketListBinding.executeBindings(FragmentTicketListBinding.java:108) 
                                                                             at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:355) `

It came to my attention that line 24 of DataBindingAdapter.java reads:

> String full_path = context.getPackageName() + "." + className;

"promo" is the name of the product flavor, so it's looking for the BR class at this location: 
**com.myproject.promo.BR**
but maybe it should be looking at this location:
**com.myproject.BR**

**Comment by jay-jlm** [comment]
I have confirmed that I no longer get the error if I manually remove the build variant identifiers from the package name like this:

`full_path = full_path.replace(".promo", "");
            full_path = full_path.replace(".client", "");`

However at this point I don't know how to automate the process.

**Comment by williamwebb** [comment]
Sorry hadn't had a chance to look into this yet. Will look into it tonight.
